version: '3.8'

services:
  ai_powered_interviewer:
    build:
      context: ./ai_powered_interview
      dockerfile: Dockerfile.dev
    volumes:
      - ./ai_powered_interview:/code
    depends_on:
      - postgres_interviewer_db
    ports:
      - "8089:8000"

  postgres_interviewer_db:
    image: postgres:latest
    restart: always
    container_name: postgres_ai_db
    environment:
      - POSTGRES_USER=ziakhan
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=mydatabase
    ports:
      - "5442:5432"
    volumes:
      - postgres_interviewer_db:/var/lib/postgresql/data

volumes:
  postgres_interviewer_db:
    driver: local
networks:
  default:
    driver: bridge    